### ISSUE TITLE
react to screen rotation

### ISSUE THREAD

**Issue by aeosynth** [Narrat/Pim#10]
if i use `xrandr` to rotate the screen, the `fullscreen` option uses the old dimensions

edit: oh, i'm a collaborator

**Comment by Narrat** [comment]
Probably because it's your old repo. I didn't touch such settings :D

**Comment by Narrat** [comment]
How do you rotate the screen?
Doing it myself with xrandr I'm not experiencing something faulty, so not sure if I miss something obvious

**Comment by aeosynth** [comment]
$ pim $PATH
    $ xrandr --output HDMI-0 --rotate left

image does not fit to screen

**Comment by aeosynth** [comment]
with rotation lock implemented, this issue doesn't affect me, closing. it is an issue though
