### ISSUE TITLE
keybind to change slideshow timer

### ISSUE THREAD

**Issue by aeosynth** [Narrat/Pim#11]
eg increase/decrease timer by 1s

**Comment by Narrat** [comment]
Particular keys in mind?

**Comment by aeosynth** [comment]
t/T, but they're used for zoom already

**Comment by Narrat** [comment]
Well. Those could be moved too.

For now I set a branch with a/A keycombination. For testing as I'm not sure currently if the timer delay should be displayed in the bars

**Comment by aeosynth** [comment]
> I'm not sure currently if the timer delay should be displayed in the bars

should

**Comment by Narrat** [comment]
New attempt, with the info in the bar.
Still to decide about the keys
