### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by aeosynth** [Narrat/Pim#19]
we probably need one

edit: pim is the last project i wrote in python, so idk how anything works, but i assume we can load the config as a python module, or we could manually parse a json file

**Comment by aeosynth** [comment]
@Narrat i'm implementing this, is there any reason Pim is a class? classes are not subscriptable, which prevents me from doing Pim[method](args)

**Comment by Narrat** [comment]
You need to ask this question yourself ;) I left the foundation work as it was and just enhanced it after I took ownership.
I didn't saw a particular benefit implementing it with a class, but it didn't bother me that much to actually change it

**Comment by aeosynth** [comment]
xD i'll make it classless

**Comment by aeosynth** [comment]
done in `next`
