### ISSUE TITLE
overlay scrollbars

### ISSUE THREAD

**Issue by aeosynth** [Narrat/Pim#21]
not sure if an app can specify overlay scrollbars, or if the theme does it. but look into this. mainly a self note.

**Comment by Narrat** [comment]
Since GTK whatever those should be mostly overlay?
They appear if needed and disappear when not in use and no mouse covering it

**Comment by Narrat** [comment]
Seems to be with 3.16
https://blogs.gnome.org/mclasen/2014/10/23/an-early-view-of-gtk-3-16/

**Comment by aeosynth** [comment]
yeah that's what i'm talking about

**Comment by Narrat** [comment]
should be default and/or from the theme then

**Comment by aeosynth** [comment]
works for me
