### ISSUE TITLE
mouse panning

### ISSUE THREAD

**Issue by aeosynth** [Narrat/Pim#22]
taken from todo comment

**Comment by Narrat** [comment]
Probably should be renamed into general mouse actions, as there were ideas for more.
Although I'm not sure about those. First one was from the old ToDo, second and third were later thought upon.
But personally I can live without mouse support.

- [ ] Panning/moving the picture on Mouse pressed (did work on that before but had kinda the impression the scroll mechanism would need a rework)

- [ ] Picture forward on simple left click

- [ ] Picture backward on simple right click

Last two should be similar to implement like your double click feature, so fairly easy. Still to decided if they're needed

**Comment by aeosynth** [comment]
last two might be harder to implement now that double-click fullscreen was implemented:

http://lazka.github.io/pgi-docs/#Gdk-3.0/enums.html#Gdk.EventType._2BUTTON_PRESS

> a mouse button has been double-clicked (clicked twice within a short period of time). Note that each click also generates a Gdk.EventType.BUTTON_PRESS event.

**Comment by Narrat** [comment]
Gah.
Well, there is still the mouse wheel :D But I suppose it would be expected to achieve a change of the zoom_level with it

**Comment by aeosynth** [comment]
we could expose double and single clicks to the user, and let them choose which they want (leave comment describing situation)

**Comment by aeosynth** [comment]
i added support for back/forward mouse button. it's possible that the buttons are specific to my mouse; if so we need a separate section for mouse binds

**Comment by Narrat** [comment]
Looks like a separate section is necessary. Those binds don't work for me at least on one of my machines.
Need to test the other ones

**Comment by aeosynth** [comment]
added mouse binds. we really need a config file now

**Comment by aeosynth** [comment]
done in `next`
