### ISSUE TITLE
rotation lock

### ISSUE THREAD

**Issue by aeosynth** [Narrat/Pim#9]
persist the rotation state for all images

**Comment by Narrat** [comment]
On first thought it seems kinda difficult, because PyGI didn't allow to rotate animations.

**Comment by aeosynth** [comment]
if you're exempting animations from rotating, keep exempting them, and lock everything else

**Comment by Narrat** [comment]
Currently I intend it to implement it like zoom lock, so any favoured key to use?

**Comment by aeosynth** [comment]
idk, maybe `Ctrl-r`

**Comment by Narrat** [comment]
Pushed to an extra branch the current WIP
Existing quirks.
 * Rotation is only saved after rotation lock is active
 * Rotation value isn't reset
 * Doesn't count how often one picture is rotated --> Even if rotated 180° the next picture will only be +/-90°

**Comment by Narrat** [comment]
Added via d9376e8
